Repository Nexters/daily-phrase-server, pull requests merged in 2024-02, with the labels that each got.

#41 Bug/40 : Cors에러 해결
  src/main/java/com/nexters/dailyphrase/config/GlobalWebConfig.java
Labels: bug

#39 Feature/34 : 관리자 글귀 목록 조회 API
  src/main/java/com/nexters/dailyphrase/admin/business/AdminFacade.java
  src/main/java/com/nexters/dailyphrase/admin/presentation/AdminApi.java
  src/main/java/com/nexters/dailyphrase/admin/presentation/dto/AdminResponseDTO.java
  src/main/java/com/nexters/dailyphrase/phrase/domain/repository/PhraseCustomRepository.java
  src/main/java/com/nexters/dailyphrase/phrase/domain/repository/PhraseCustomRepositoryImpl.java
  src/main/java/com/nexters/dailyphrase/phrase/implement/PhraseCommandService.java
  src/main/java/com/nexters/dailyphrase/phrase/implement/PhraseQueryService.java
  src/test/java/com/nexters/dailyphrase/admin/business/AdminApiIntegretionTest.java
Labels: feature

#44 Feature/42 : 요청 Validation
  src/main/java/com/nexters/dailyphrase/admin/business/AdminFacade.java
  src/main/java/com/nexters/dailyphrase/admin/business/AdminMapper.java
  src/main/java/com/nexters/dailyphrase/common/enums/SocialType.java
  src/main/java/com/nexters/dailyphrase/common/presentation/converter/SocialTypeRequestConverter.java
  src/main/java/com/nexters/dailyphrase/config/GlobalWebConfig.java
  src/main/java/com/nexters/dailyphrase/phrase/implement/PhraseCommandService.java
  src/main/java/com/nexters/dailyphrase/phrase/presentation/PhraseApi.java
  src/test/java/com/nexters/dailyphrase/admin/business/AdminApiIntegretionTest.java
Labels: feature

#50 Bug/49 : 회원 탈퇴 500 에러
  src/main/generated/com/nexters/dailyphrase/admin/domain/QAdmin.java
  src/main/java/com/nexters/dailyphrase/admin/business/AdminFacade.java
  src/main/java/com/nexters/dailyphrase/admin/business/AdminMapper.java
  src/main/java/com/nexters/dailyphrase/admin/domain/repository/AdminRepository.java
  src/main/java/com/nexters/dailyphrase/common/jwt/JwtAuthorizationFilter.java
  src/main/java/com/nexters/dailyphrase/common/jwt/JwtTokenService.java
  src/main/java/com/nexters/dailyphrase/config/SecurityConfig.java
  src/main/java/com/nexters/dailyphrase/favorite/domain/repository/FavoriteRepository.java
  src/main/java/com/nexters/dailyphrase/favorite/implement/FavoriteCommandService.java
  src/main/java/com/nexters/dailyphrase/favorite/implement/FavoriteQueryService.java
  src/main/java/com/nexters/dailyphrase/member/business/MemberFacade.java
  src/main/java/com/nexters/dailyphrase/phrase/domain/repository/PhraseCustomRepository.java
  src/test/java/com/nexters/dailyphrase/admin/business/AdminApiIntegretionTest.java
  src/test/java/com/nexters/dailyphrase/member/presentation/MemberApiIntegretionTest.java
Labels: bug

#52 Bug/51 : 스웨거 설정 열어주기
  src/main/java/com/nexters/dailyphrase/config/SecurityConfig.java
Labels: bug

#54 Feature/53 : 글귀 상세조회 응답 필드 추가
  src/main/java/com/nexters/dailyphrase/common/consts/DailyPhraseStatic.java
  src/main/java/com/nexters/dailyphrase/common/jwt/JwtAuthorizationFilter.java
  src/main/java/com/nexters/dailyphrase/phrase/business/PhraseMapper.java
  src/main/java/com/nexters/dailyphrase/phrase/presentation/dto/PhraseResponseDTO.java
Labels: bug, feature

#56 Feature/55 : 좋아요 개수 필드 추가
  src/main/java/com/nexters/dailyphrase/like/business/LikeFacade.java
  src/main/java/com/nexters/dailyphrase/like/business/LikeMapper.java
  src/main/java/com/nexters/dailyphrase/like/domain/repository/LikeRepository.java
  src/main/java/com/nexters/dailyphrase/like/implement/LikeQueryService.java
  src/main/java/com/nexters/dailyphrase/like/presentation/dto/LikeResponseDTO.java
  src/main/java/com/nexters/dailyphrase/phrase/business/PhraseFacade.java
  src/main/java/com/nexters/dailyphrase/phrase/business/PhraseMapper.java
  src/main/java/com/nexters/dailyphrase/phrase/presentation/dto/PhraseResponseDTO.java
Labels: feature

#57 Feature/38 : 사용자 인가처리 & 글귀 상세/목록 조회 응답 필드 추가
  src/main/java/com/nexters/dailyphrase/common/utils/MemberUtils.java
  src/main/java/com/nexters/dailyphrase/common/utils/SecurityUtils.java
  src/main/java/com/nexters/dailyphrase/config/SecurityConfig.java
  src/main/java/com/nexters/dailyphrase/favorite/domain/repository/FavoriteRepository.java
  src/main/java/com/nexters/dailyphrase/favorite/implement/FavoriteQueryService.java
  src/main/java/com/nexters/dailyphrase/like/domain/repository/LikeRepository.java
  src/main/java/com/nexters/dailyphrase/like/implement/LikeQueryService.java
  src/main/java/com/nexters/dailyphrase/phrase/business/PhraseFacade.java
  src/main/java/com/nexters/dailyphrase/phrase/business/PhraseMapper.java
  src/main/java/com/nexters/dailyphrase/phrase/domain/repository/PhraseCustomRepositoryImpl.java
  src/main/java/com/nexters/dailyphrase/phrase/presentation/dto/PhraseResponseDTO.java
Labels: feature

#61 Feature/48 이미지 업로드 API
  build.gradle
  src/main/java/com/nexters/dailyphrase/admin/business/AdminFacade.java
  src/main/java/com/nexters/dailyphrase/admin/business/AdminMapper.java
  src/main/java/com/nexters/dailyphrase/admin/exception/AdminBadCredentialException.java
  src/main/java/com/nexters/dailyphrase/admin/presentation/AdminApi.java
  src/main/java/com/nexters/dailyphrase/admin/presentation/dto/AdminRequestDTO.java
  src/main/java/com/nexters/dailyphrase/admin/presentation/dto/AdminResponseDTO.java
  src/main/java/com/nexters/dailyphrase/config/S3Config.java
  src/main/java/com/nexters/dailyphrase/phrase/domain/Phrase.java
  src/main/java/com/nexters/dailyphrase/phrase/presentation/PhraseApi.java
  src/main/java/com/nexters/dailyphrase/phraseimage/domain/PhraseImage.java
  src/main/resources/application.yml
Labels: feature

#64 Ci/63: 프로파일 변경
  src/main/generated/com/nexters/dailyphrase/phraseimage/domain/QPhraseImage.java
  src/main/java/com/nexters/dailyphrase/phrase/presentation/PhraseApi.java
  src/main/resources/application.yml
Labels: ci

#65 Ci/63: application.yml 수정
  src/main/resources/application.yml
Labels: ci

#66 Feature/62 : 즐겨찾기 목록 조회 응답 필드 추가
  src/main/java/com/nexters/dailyphrase/favorite/domain/repository/FavoriteCustomRepositoryImpl.java
  src/main/java/com/nexters/dailyphrase/favorite/presentation/dto/FavoriteResponseDTO.java
Labels: feature

#70 fix/69 content 글자수 제한 오류 수정
  src/main/java/com/nexters/dailyphrase/phrase/domain/Phrase.java
Labels: bug

#68 fix/64 관리자 API CORS 오류 수정
  src/main/java/com/nexters/dailyphrase/config/GlobalWebConfig.java
  src/main/java/com/nexters/dailyphrase/phrase/domain/Phrase.java
Labels: bug

#72 fix: 서버 기동 오류 수정
  build.gradle
  src/main/java/com/nexters/dailyphrase/config/S3Config.java
  src/test/java/com/nexters/dailyphrase/phrase/business/PhraseFacadeIntegrationTest.java
Labels: bug

#73 fix/71: 서버 기동오류 수정-롤백
  src/main/java/com/nexters/dailyphrase/config/GlobalWebConfig.java
  src/main/java/com/nexters/dailyphrase/config/S3Config.java
  src/main/java/com/nexters/dailyphrase/phrase/domain/Phrase.java
Labels: bug

#75 Feature/74 : 글귀 내용 길이 조정
  src/main/java/com/nexters/dailyphrase/phrase/domain/Phrase.java
  src/test/java/com/nexters/dailyphrase/phrase/business/PhraseFacadeIntegrationTest.java
Labels: feature

#77 fix: CORS 정책 설정-인증 허용
  src/main/java/com/nexters/dailyphrase/config/GlobalWebConfig.java
Labels: bug

#79 Feature/78 : 글귀 목록 / 상세 조회 필드 추가
  src/main/java/com/nexters/dailyphrase/config/GlobalWebConfig.java
  src/main/java/com/nexters/dailyphrase/phrase/business/PhraseMapper.java
  src/main/java/com/nexters/dailyphrase/phrase/domain/repository/PhraseCustomRepositoryImpl.java
  src/main/java/com/nexters/dailyphrase/phrase/presentation/dto/PhraseResponseDTO.java
Labels: feature

#81 Feature/80:Security Config 예외처리 추가
  src/main/java/com/nexters/dailyphrase/admin/exception/AdminErrorCode.java
  src/main/java/com/nexters/dailyphrase/admin/exception/AdminForbiddenException.java
  src/main/java/com/nexters/dailyphrase/admin/exception/AdminUnauthorizedException.java
  src/main/java/com/nexters/dailyphrase/config/GlobalWebConfig.java
  src/main/java/com/nexters/dailyphrase/config/SecurityConfig.java
Labels: feature

#84 fix/84: CORS 정책 수정-preflight 허용
  src/main/java/com/nexters/dailyphrase/admin/presentation/AdminApi.java
  src/main/java/com/nexters/dailyphrase/config/GlobalWebConfig.java
  src/main/java/com/nexters/dailyphrase/config/SecurityConfig.java
  src/main/java/com/nexters/dailyphrase/member/presentation/MemberApi.java
Labels: bug

#86 Feature/86: 관리자 글귀목록 조회 응답 필드 추가
  src/main/java/com/nexters/dailyphrase/admin/business/AdminMapper.java
  src/main/java/com/nexters/dailyphrase/admin/presentation/dto/AdminRequestDTO.java
  src/main/java/com/nexters/dailyphrase/admin/presentation/dto/AdminResponseDTO.java
  src/main/java/com/nexters/dailyphrase/phrase/domain/repository/PhraseCustomRepositoryImpl.java
Labels: feature

#88 fix/88: 관리자 글 삭제 API 수정
  src/main/java/com/nexters/dailyphrase/admin/business/AdminFacade.java
  src/main/java/com/nexters/dailyphrase/admin/business/AdminMapper.java
  src/main/java/com/nexters/dailyphrase/admin/presentation/AdminApi.java
  src/main/java/com/nexters/dailyphrase/admin/presentation/dto/AdminResponseDTO.java
  src/main/java/com/nexters/dailyphrase/favorite/domain/repository/FavoriteRepository.java
  src/main/java/com/nexters/dailyphrase/favorite/implement/FavoriteCommandService.java
  src/main/java/com/nexters/dailyphrase/like/domain/repository/LikeRepository.java
  src/main/java/com/nexters/dailyphrase/like/implement/LikeCommandService.java
Labels: bug

#89 Feature/90: 관리자 글귀 목록 조회 응답 필드 추가(2)
  src/main/java/com/nexters/dailyphrase/admin/business/AdminMapper.java
  src/main/java/com/nexters/dailyphrase/admin/presentation/dto/AdminRequestDTO.java
  src/main/java/com/nexters/dailyphrase/admin/presentation/dto/AdminResponseDTO.java
  src/main/java/com/nexters/dailyphrase/phrase/domain/repository/PhraseCustomRepositoryImpl.java
Labels: feature

#90 Fix: #88, #89 merge
  src/main/java/com/nexters/dailyphrase/admin/business/AdminFacade.java
  src/main/java/com/nexters/dailyphrase/admin/business/AdminMapper.java
  src/main/java/com/nexters/dailyphrase/admin/presentation/AdminApi.java
  src/main/java/com/nexters/dailyphrase/admin/presentation/dto/AdminRequestDTO.java
  src/main/java/com/nexters/dailyphrase/admin/presentation/dto/AdminResponseDTO.java
  src/main/java/com/nexters/dailyphrase/favorite/domain/repository/FavoriteRepository.java
  src/main/java/com/nexters/dailyphrase/favorite/implement/FavoriteCommandService.java
  src/main/java/com/nexters/dailyphrase/like/domain/repository/LikeRepository.java
  src/main/java/com/nexters/dailyphrase/like/implement/LikeCommandService.java
  src/main/java/com/nexters/dailyphrase/phrase/domain/repository/PhraseCustomRepositoryImpl.java
Labels: duplicate

#91 Feature/92: 로깅(log4j2) 설정 추가
  build.gradle
  src/main/resources/log4j2.xml
Labels: feature

#95 fix/93: 글귀 수정 API 이미지url 오류 수정
  src/main/java/com/nexters/dailyphrase/admin/business/AdminFacade.java
  src/main/java/com/nexters/dailyphrase/phraseimage/domain/PhraseImage.java
Labels: bug

#98 Feature/97 : 글 예약 발행
  src/main/generated/com/nexters/dailyphrase/phrase/domain/QPhrase.java
  src/main/java/com/nexters/dailyphrase/DailyphraseApplication.java
  src/main/java/com/nexters/dailyphrase/admin/business/AdminFacade.java
  src/main/java/com/nexters/dailyphrase/admin/business/AdminMapper.java
  src/main/java/com/nexters/dailyphrase/admin/presentation/AdminApi.java
  src/main/java/com/nexters/dailyphrase/admin/presentation/dto/AdminRequestDTO.java
  src/main/java/com/nexters/dailyphrase/admin/presentation/dto/AdminResponseDTO.java
  src/main/java/com/nexters/dailyphrase/job/PhraseScheduler.java
  src/main/java/com/nexters/dailyphrase/member/presentation/MemberApi.java
  src/main/java/com/nexters/dailyphrase/phrase/business/PhraseFacade.java
  src/main/java/com/nexters/dailyphrase/phrase/domain/Phrase.java
  src/main/java/com/nexters/dailyphrase/phrase/domain/repository/PhraseCustomRepositoryImpl.java
  src/main/java/com/nexters/dailyphrase/phrase/domain/repository/PhraseRepository.java
  src/main/java/com/nexters/dailyphrase/phrase/implement/PhraseQueryService.java
Labels: feature
